[package]
name = "cck"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cck"
path = "./src/lib.rs"

[[bin]]
name = "cck"
path = "./src/bin/main.rs"

[dependencies]

#https://github.com/rust-random/
rand = "0.8.5"
rand_chacha = "0.3.1"

#https://github.com/RustCrypto/traits/
aead = { version = "0.5.2", features=["arrayvec"] }

#https://github.com/RustCrypto/AEADs/
chacha20poly1305 = "0.10.1"

[features]
alloc = ["aead/alloc"]

