# temporary automation work
git rm ./src/benches/asymmetric.rs
git rm ./src/benches/compress.rs
git rm ./src/benches/format.rs
git rm ./src/benches/hash.rs
git rm ./src/benches/rand.rs
git rm ./src/benches/symmetric.rs
git rm ./src/tests/hash.rs
git rm ./src/asymmetric/ed25519.rs
git rm ./src/asymmetric/mod.rs
git rm ./src/asymmetric/x25519.rs
git rm ./src/bin/broker/main.rs
git rm ./src/bin/cli/main.rs
git rm ./src/compress/deflate.rs
git rm ./src/compress/mod.rs
git rm ./src/format/base64ct.rs
git rm ./src/format/hex.rs
git rm ./src/format/mod.rs
git rm ./src/format/pem.rs
git rm ./src/hash/blake3.rs
git rm ./src/hash/mod.rs
git rm ./src/hash/sha2.rs
git rm ./src/key_ring/key.rs
git rm ./src/key_ring/mod.rs
git rm ./src/lib.rs
git rm ./src/rand.rs
git rm ./src/size.rs
git rm ./src/symmetric/aead.rs
git rm ./src/symmetric/aes.rs
git rm ./src/symmetric/chacha.rs
git rm ./src/symmetric/mod.rs
git add ./Cargo.toml
git add ./crates/cck-asymmetric
git add ./crates/cck-common
git add ./crates/cck-compress
git add ./crates/cck-format
git add ./crates/cck-hash
git add ./crates/cck-symmetric
git add ./crates/keyring
git commit -m "all cleanup" -m "all work up to this commit has been cleaned up in order to properly split crate(lib). work in ./src/* has been moved to ./crates/*., ./Cargo.toml cleaned and workspace written., remove ./src ./benches ./tests, add ./crates/, update ./Cargo.toml"