[package]
name = "cck-rand"
version = "0.0.1"
edition = "2021"

[dependencies]
#https://github.com/rust-random/
rand = "0.8.5"
rand_chacha = "0.3.1"

#Internal
cck-common={path="../cck-common",version="0.0.1"}
